language: python
python:
    - "3.8"
    - "3.9"
    - "3.9-dev" # 3.9 development branch 
    - "nightly" #nightly build

#Command to install dependencies
install: 
    - pip install -r requirements.txt

env:
    - ENV="development"
    - ENV="production" ; SESSION_SECRET="secret12345"

services:
    - postgresql

# Command to run tests
script:
  - make test
  - make lint 
